### ISSUE TITLE
Processing doesn't stop when "side location conflict" error is encountered

### ISSUE THREAD

**Issue by sachabaclet** [Ifsttar/NoiseModelling#270] opened 2020-12-10 16:24 UTC
Hi!

**NoiseModelling version**
NoiseModelling 3.3.1

**Describe the bug**
When a "side location conflict" is encountered while running a simulation, the processing doesn't stop. Instead, it keeps going, not showing anything unusual in the command window or the log for the following cells. 
However, it doesn't calculate any kind of sound propagation for the cells that follow. It does create an LDAY_GEOM table at the end, but it only contains the cells that were processed _before_ the error occurred.

Here is what it looks like:
```
2020-12-08 19:02:12,051 INFO [noise_planet.noisemodelling] - Compute domain is POLYGON ((673280.7639242328 6582118.940078115, 673280.7639242328 6582450.948441044, 673669.7269918799 6582450.948441044, 673669.7269918799 6582118.940078115, 673280.7639242328 6582118.940078115))
2020-12-08 19:02:12,051 INFO [noise_planet.noisemodelling] - Compute... 64.153 % (133 receivers in this cell)
2020-12-08 19:02:12,051 INFO [jdbc.PointNoiseMap] - Begin processing of cell 2662 / 4096
2020-12-08 19:02:12,335 INFO [jdbc.PointNoiseMap] - This computation area contains 133 receivers 5331 sound sources and 107 buildings
2020-12-08 19:02:12,357 ERROR [propagation.ComputeRays] - side location conflict [ (673503.0033130886, 6582260.725790114, NaN) ]
org.locationtech.jts.geom.TopologyException: side location conflict [ (673503.0033130886, 6582260.725790114, NaN) ]
	at org.locationtech.jts.geomgraph.EdgeEndStar.propagateSideLabels(EdgeEndStar.java:286)
	at org.locationtech.jts.geomgraph.EdgeEndStar.computeLabelling(EdgeEndStar.java:122)
	[...many lines of errors...]

2020-12-08 19:02:12,360 INFO [propagation.RootProgressVisitor] - 64.16 %
2020-12-08 19:02:12,362 INFO [noise_planet.noisemodelling] - Compute domain is POLYGON ((673280.7639242328 6582450.948441045, 673280.7639242328 6582782.956803975, 673669.7269918799 6582782.956803975, 673669.7269918799 6582450.948441045, 673280.7639242328 6582450.948441045))
2020-12-08 19:02:12,362 INFO [noise_planet.noisemodelling] - Compute... 64.220 % (111 receivers in this cell)
2020-12-08 19:02:12,362 INFO [jdbc.PointNoiseMap] - Begin processing of cell 2663 / 4096
2020-12-08 19:02:12,553 INFO [jdbc.PointNoiseMap] - This computation area contains 111 receivers 4814 sound sources and 89 buildings
[keeps going normally]
```

**Geoserver log**
[geoserver.log](https://github.com/Ifsttar/NoiseModelling/files/5674163/geoserver.log)

**Expected behavior**
That behavior would be acceptable if NoiseModelling "ignored" the invalid building(s) and kept going normally afterwards.
However, given that it stops calculating any propagation after that, I'd expect NoiseModelling to exit the processing and display an error.

**Comment by pierromond** [comment] 2020-12-11 08:45
Hi Sacha,

Did you try the block "Clean_buildings" before beginning the calculation ?

Also, now in this last version, you have acces to the building : [ (673503.0033130886, 6582260.725790114, NaN) ] so you can remove it or check what happens there (and even extract the zone and send us a small dataset to try to fix this problem).

Finally do you use OSM buildings ? If yes, we did a more robust script to import OSM databse from BBBike provider. You can find it here : https://github.com/pierromond/NoiseModelling/blob/FixImportOSMBBBike/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Import_and_Export/Import_OSM_BBBike.groovy

Regards,

**Comment by sachabaclet** [comment] 2020-12-15 12:54
Hi Pierre,

I tried the "Clean_buildings" tool at some point, and it worked, but unfortunately, it completely removes some buildings from my dataset, so I decided not to use it anymore.

Instead, I use a (self-made) Python script which imports OSM data and pre-processes the buildings (adding height when it's not available in OSM, applying a buffer to smoothen sharp angles, "dissolving" polygons to make sure that there are no overlapping buildings, converting multi-polygons to single polygons, adding population data...). Unfortunately, as you can see, it's not 100% reliable. 

I am not sure what exactly causes errors. 
Sometimes, it seems to happen when 2 buildings are very close (a few centimeters) but not overlapping. 
Sometimes, it's when there's a _very_ sharp angle in the shape of a building.
At other times, I can't exactly figure out what is the cause; it usually happens on convex surfaces or surfaces with somewhat sharp (<90°) angles.
In those cases, I just manually edit the shape of the building so that the error disappears, and it works most of the time.

Do you know exactly what in the processing of NoiseModelling usually causes errors with buildings, so that I can make sure that they don't arise anymore? Overlapping buildings was a cause, but I have now eliminated it.

If that happens again, I will send you send you samples so that you can see for yourself.

Thanks for the BBBike script, I didn't know that it existed!

**Comment by pierromond** [comment] 2020-12-16 08:47
I tried the "Clean_buildings" tool at some point, and it worked, but unfortunately, it completely removes some buildings from my dataset, so I decided not to use it anymore.
> Yes, it is what it does... Damaging but effective.

Instead, I use a (self-made) Python script which imports OSM data and pre-processes the buildings (adding height when it's not available in OSM, applying a buffer to smoothen sharp angles, "dissolving" polygons to make sure that there are no overlapping buildings, converting multi-polygons to single polygons, adding population data...). Unfortunately, as you can see, it's not 100% reliable.
> A colleague @ebocher , geomatic expert also did sthg, but for the moment we can't include it directly in NoiseModelling, but probably next year it will be part of it #221 . You can find it here -> https://github.com/orbisgis/geoclimate/blob/master/osm/src/main/groovy/org/orbisgis/orbisprocess/geoclimate/osm/OSMGISLayers.groovy

I am not sure what exactly causes errors.
Sometimes, it seems to happen when 2 buildings are very close (a few centimeters) but not overlapping.
Sometimes, it's when there's a very sharp angle in the shape of a building.
At other times, I can't exactly figure out what is the cause; it usually happens on convex surfaces or surfaces with somewhat sharp (<90°) angles.
In those cases, I just manually edit the shape of the building so that the error disappears, and it works most of the time.
Do you know exactly what in the processing of NoiseModelling usually causes errors with buildings, so that I can make sure that they don't arise anymore? Overlapping buildings was a cause, but I have now eliminated it.
> Yes we know that this is the triangulation step the error. We planned to pass to octree to avoid this errors #224 ... Hope next year also...

If that happens again, I will send you send you samples so that you can see for yourself.
> Thank you !

Thanks for the BBBike script, I didn't know that it existed!
> It will be published in the next release ;)

I close this issue and relate it to #224

**Closed by pierromond** 2020-12-16 08:47 UTC
Labels: bug
